# @package _global_

defaults:
  - _self_

model_name: MPNN_Backbone_3SAT_200
model_dir: runs/${model_name}

from_checkpoint: null

training:
  epochs: 50
  use_amp: True

dataset:
  train_path: "data/training/3sat/200/unsat/*.cnf"
  val_path: "data/validation/3sat/200/unsat/*.cnf"
  num_workers: 15
  target: backbone

model:
  channels: 256
  num_layers: 10
  aggr: [mean]
  global_aggr: null

loader:
  batch_size: 20
  num_workers: 0

optim:
  lr: 1e-4
  weight_decay: 0.1
  lr_min: 1e-6
  warmup_ratio: 0.01

wandb:
  project: RLAF
  name: ${model_name}


# path to original working directory
work_dir: ${hydra:runtime.cwd}

# path to folder with data
data_dir: data

# seed for random number generators in pytorch, numpy and python.random
seed: 1729
